import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./providers";

// METADATA --------------------------------------------------------------------------------------------------------------------------------
export const metadata: Metadata = {
	title: "next-rhf-effect",
	description: "Generated by create next app",
};

// ROOT ------------------------------------------------------------------------------------------------------------------------------------
export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className="antialiased">
				<Providers attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<nav className="p-2 flex gap-2 items-center justify-center">
						<Button asChild variant="ghost">
							<Link href="/">Home</Link>
						</Button>
						<Button asChild variant="ghost">
							<Link href="/zod">Zod</Link>
						</Button>
						<Button asChild variant="ghost">
							<Link href="/zod-mini">Zod Mini</Link>
						</Button>
						<Button asChild variant="ghost">
							<Link href="/effect">Effect</Link>
						</Button>
					</nav>
					<div className="bg-muted flex min-h-svh flex-col items-center justify-center p-6 md:p-10">{children}</div>
					<Toaster richColors />
				</Providers>
			</body>
		</html>
	);
}
