import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./providers";

// METADATA --------------------------------------------------------------------------------------------------------------------------------
export const metadata: Metadata = {
	title: "next-rhf-effect",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className="antialiased">
				<Providers attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					{children}
					<Toaster richColors />
				</Providers>
			</body>
		</html>
	);
}
